config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'geebook' => 'home#geebook'
  devise_for :users
  get 'pie' => 'pie#index'
  resources :posts
  mount FruitAPI::API => '/'

end

app/models/fruit.rb
class Fruit < ActiveRecord::Base
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :userfruits
	accepts_nested_attributes_for :userfruits
	has_attached_file :photo, styles: { large: "600x600>", medium: "300x300", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

  include Gravtastic
  gravtastic

end

app/models/userfruit.rb
class Userfruit < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def search
  end

  def geekbook
  end
end

app/controllers/pie_controller.rb
class PieController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :check_login, only: [:index, :show, :update, :destroy]

  

  def check_login  
    if !current_user  
     redirect_to new_user_session_path  
    end  
  end 

  # GET /posts
  # GET /posts.json
  def index
    @posts = current_user.posts
    # if @post.fruitlist.present?
    #   @fruit_tag = @post.fruitlist.split(',')
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
     # binding.pry
    if @post.fruitlist.present?
      @fruit_tag = @post.fruitlist.split(',')
    end
      @heat = 0.0
      @water= 0.0
      @protein= 0.0
      @fat= 0.0
      @carbohydrate= 0.0
      @fiber= 0.0
      @sugar= 0.0
      @na = 0.0
      @k= 0.0
      @ca= 0.0
      @mg= 0.0
      @fe= 0.0
      @zn= 0.0
      @p= 0.0
      @va= 0.0
      @ve= 0.0
      @vb= 0.0
      @vc= 0.0
      @fruit_tag.each do |fu|
        f = Fruit.find_by_name(fu)
        @heat += f.heat
        @water+= f.water
        @protein+=  f.protein
        @fat+= f.fat
        @carbohydrate+= f.carbohydrate
        @fiber+=  f.fiber
        @sugar+=  f.sugar
        @na +=  f.na
        @k+=  f.k
        @ca+=  f.ca 
        @mg+=  f.mg   
        @fe+=  f.fe
        @zn+=  f.zn
        @p+=   f.p
        @va+=  f.va
        @ve+=  f.ve
        @vb+=  f.vb
        @vc+=  f.vc

        # {vc: "", vb: , }
    end
    @big_v_h = {vc: @va, vb: @vb, vc: @vc, ve: @ve}.max_by{|k,v| v}
    @min_v_h = {vc: @va, vb: @vb, vc: @vc, ve: @ve}.min_by{|k,v| v}
    # binding.pry
    @big_m_h = {mg: @mg, ca: @ca, k: @k, fe: @fe, zn: @zn, p: @p  }.max_by{|k,v| v}
    @min_m_h = {mg: @mg, ca: @ca, k: @k, fe: @fe, zn: @zn, p: @p  }.min_by{|k,v| v}
    

    @v_need= {
      va: "小番茄",
      vb: "榴槤",
      vc: "芭樂"
    }

    @m_need ={
      mg: "榴槤", ca: "桑葚", k: "榴槤", fe: "小番茄", zn: "枇杷", p:  "百香果" 
    }

    @energy_name= {heat:"熱量", fiber:"膳食纖維", na:"鈉", k:"鉀", ca:"鈣", mg:"鎂", fe:"鐵", zn:"鋅", p:"磷", va:"維生素A", ve:"維生素E", vc: "維生素C", vb: "維生素B"}


  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create

    @post = Post.new(post_params)
    if post_params[:eat_time].present?
      date_arr = post_params[:eat_time].split("/")
      arr =[] 
      arr << date_arr[2] << date_arr[0] << date_arr[1] 
      @post.eat_time = DateTime.parse(arr.join('-'))
      @post.save
    end
    
    ap @post
    
    if params[:userfruits].present?
      fruitlist = params[:userfruits].join(",")
      @post.fruitlist = fruitlist
      @post.save
    end

    
    respond_to do |format| 
      if @post.save
        
        current_user.posts << @post
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
        # binding.pry
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end 

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:content,:photo,:eat_time)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
	 def create
			auth  =request.env["omniauth.auth"] #callback from facebook,twitter...
			# session[:omniauth] = auth.except('extra')
			# user = User.sign_in_from_omniauth(auth)
			if auth.info.email.present?
			# 如果沒帳號就建立一個
				if User.find_by_email(auth.info.email).nil? 
					User.create(email: auth.info.email, password: auth.info.email)
				end
				current_user = User.find_by_email(auth.info.email)
			end

	        redirect_to root_url, notice: "Sign in"
	        binding.pry
	end

	def destroy
		session[:user_id] = nil
		session[:omniauth] = nil
		redirect_to root_url, notice: "Sign out"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def geebook_block(picture_path)

  end
end

app/helpers/pie_helper.rb
module PieHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/home/index.html.erb
<body id="page-top" class="index" style="background: #63E5D5">
  <!-- Header -->
  <header>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= image_tag('img/logologo.png', :class => 'img-responsive', :alt => '', :width => '256', :height => '256') %>
          <div class="intro-text">
            <span class="name">Golly Gee 果力力</span>
            <span class="sub-name">你的營養小秘書，給你一天的活力！</span>
          </div>
        </div>
      </div>
    </div>
  </header>
  <!-- Portfolio Grid Section -->
  <div>
    <div class="row">
      <div class="col-lg-2">
        <%= image_tag('img/Illustrations/1-3.png', :class => 'img-responsive', :alt => '', :height => '285') %>
      </div>
      <div class="col-lg-8 text-center" style="padding-top: 6%;">
        <h3>Diary</h3>
        <h5>紀錄你的每日水果攝取，幫你計算營養均衡，還可以解鎖Geebook稀有水果怪物唷！</h5>
      </div>
      <div class="col-lg-2">
        <a href="http://localhost:3000/">
          <%= image_tag('img/Illustrations/1.png', :class => 'img-responsive', :id => 'set1') %>
        </a>
      </div>
    </div>
  </div>
  <!-- About Section -->
  <div>
    <div class="row" style="background: #FFEF2C;">
      <div class="col-lg-2">
        <a href="Illustrations.html">
          <%= image_tag('img/Illustrations/2.png', :class => 'img-responsive', :id => 'set2') %>
        </a>
      </div>
      <div class="col-lg-8 text-center" style="padding-top: 6%;">
        <h3>Geebook</h3>
        <h5>幫你分析水果營養成分，每日登入並記錄你的水果攝取<br>獲得經驗值以解鎖稀有水果怪物，水果怪物在圖鑑等你收集！</h5>
      </div>
      <div class="col-lg-2">
        <%= image_tag('img/Illustrations/2-3.png', :class => 'img-responsive', :alt => '') %>
      </div>
    </div>
  </div>
  <!-- Contact Section -->
  <div>
    <div class="row">
      <div class="col-lg-2">
        <%= image_tag('img/Illustrations/2-4.png', :class => 'img-responsive', :alt => '') %>
      </div>
      <div class="col-lg-8 text-center" style="padding-top: 6%;">
        <h3>Search</h3>
        <h5>消化不良？火氣大？還是小感冒？搜尋你的症狀，惱人的小毛病用水果來對抗<br>
          探訪長輩、節慶致意，找不到合適的禮物？Golly Gee告訴你哪些水果最適合！</h5>
      </div>
      <div class="col-lg-2">
        <a href="search.html">
          <%= image_tag('img/Illustrations/3.png', :class => 'img-responsive', :id => 'set3') %>
        </a>
      </div>
    </div>
  </div>

  <script type="text/javascript">
    $(document).ready(function () {
      $("#set1").mouseenter(function () {
        $("#set1").attr("src", "<%= image_path("img/Illustrations/1-2.png")%>");
      });
      $("#set1").mouseleave(function () {
        $("#set1").attr("src", "<%= image_path("img/Illustrations/1.png")%>");
      });
      $("#set2").mousemove(function () {
        $("#set2").attr("src", "<%= image_path("img/Illustrations/2-2.png")%>");
      });
      $("#set2").mouseleave(function () {
        $("#set2").attr("src", "<%= image_path("img/Illustrations/2.png")%>");
      });
      $("#set3").mousemove(function () {
        $("#set3").attr("src", "<%= image_path("img/Illustrations/3-3.png")%>");
      });
      $("#set3").mouseleave(function () {
        $("#set3").attr("src", "<%= image_path("img/Illustrations/3.png")%>");
      });
    });
  </script>
</body>

app/views/home/search.html.erb
<h1>Home#search</h1>
<p>Find me in app/views/home/search.html.erb</p>

app/views/pie/index.html.erb
<h1>Pie#index</h1>
<p>Find me in app/views/pie/index.html.erb</p>

<%#= image_tag('agriblack.png', :class => "img_preview", :alt => "alttt") %>

<%= image_tag('agriblack.png', :class => 'btn btn-primary', :alt => 'alt-attribute')%>

app/views/posts/_form.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading clearfix">
      <h3 class="panel-title pull-left">NewPost</h3>
    </div>
    <div class="modal-body">
     <%= form_for(@post, class: "form-horizontal",  html: { multipart: true })  do |f| %>
     <% if @post.errors.any? %>
     <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <!-- <form class="form-horizontal"> -->
    <div class="form-group ">
      <label class="col-xs-3 control-label">Upload</label>
      <div class="col-xs-9">
        <%= f.file_field :photo, :class => "form-control form_padding"  %>
        <!-- <input type="file" accept="image/*" class="form-control" > -->
      </div>
    </div>
    <div class="form-group ">
      <label class="col-xs-3 control-label">Tags</label>
      <div class="col-xs-9">
        <input id="project" class = "form-control form_padding">
        <span id = "fruit_tag"> </span>
        <div id = "fruit_input"></div>
        <!-- <input type="text" class="form-control" placeholder=""> -->
      </div>
    </div>
    <div class="form-group">
      <label class="col-xs-3 control-label">Date</label>
      <div class="col-xs-9" class = "form-control">
        <!-- <input type="date" data-required="true" required>   -->
        <%= f.text_field :eat_time, :class => "form-control form_padding", "data-provide" => 'datepicker' %>
      </div>
    </div>
    <div class="form-group">
      <label class="col-xs-3 control-label">Context</label>
      <div class="col-xs-9" >
        <!-- <textarea class="form-control" rows="3" placeholder=""></textarea> -->
        <%= f.text_area :content , class: "form-control form_padding", rows: "3"%>
      </div>
    </div>
  <div class="panel-footer">
  <div class="btn-group pull-right">
    
      <%= link_to "Cancle", posts_path , class: "btn btn-danger form_padding"%>
      <%= f.submit "Create", class: "btn btn-success form_padding" , style: "background:#0275d8" do %>
        <i class="fa fa-check"></i>
      <% end %>
  </div>
</div>
</div>

</div>
<% end %>
</div>






<!--  -->


<script>
  $( function() {

    var availableTags = ["木瓜", "青木瓜", "椰子汁", "百香果", "西瓜", "李子", "芒果", "金黃奇異果", "奇異果", "枇杷", "甜柿", "萊姆", "檸檬汁", "文旦", "柳橙", "椪柑", "火龍果", "香蕉", "桑葚", "桑葚汁", "水蜜桃", "荔枝", "草莓", "西洋梨", "水梨", "甜瓜,香瓜", "蜜棗", "芭樂", "大番茄", "小番茄", "楊桃", "葡萄", "酪梨", "鳳梨", "蓮霧", "龍眼", "蘋果", "釋迦", "番石榴", "紅毛丹", "榴槤", "櫻桃"];

    // var availableTags = ["papaya", "Green Papaya", "coconut", "Granadilla", "watermelon"];

    
    $( "#project" ).autocomplete({
      minLength: 0,
      source: availableTags,
      focus: function( event, ui ) {
        $( "#project" ).val(ui.item.label);
        return false;
      },
      select: function( event, ui ) {
        $( "#project" ).val( ui.item.label );
        // <span class="label label-success">Success</span>
        $("#fruit_tag").append("<span style=\"margin: 6px\"class=\"label label-success\">#"+ ui.item.label +"</span>");
        $("#fruit_input").append(
          $('<input>', {
            type: 'hidden',
            name: 'userfruits[]',
            val: ui.item.label
          })
          );
        $("#project").val("");
        return false;
      }
    })
    .autocomplete( "instance" )._renderItem = function( ul, item ) {
      return $( "<li>" )
      .append( "<button class = \"btn btn-default\">" + item.label  + "</button>" )
      .appendTo( ul );
    };
  } );
</script>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<section id="portfolio" style="padding-bottom:20px;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>Diary</h2>
                    <hr class="star-primary">
                </div>
            </div>
        </div>
</section>

 <div class="container">
        <div class="row">
            <div class="col-md-12">
               
             
                <%= link_to "PostNew", new_post_path, class: "btn btn-lg btn-danger" %>
               <hr>
            </div>
        </div>

        <div class="row">
        <% @posts.each_with_index do |post, index| %>
        <% if index % 3 == 2 %>
          <div class ="row">
        <% end %>        
            <div class="col-md-4 col-sm-6">
                <div class="panel panel-default">
                      <div class="panel-heading clearfix">
                         
                        
                        <% if post.eat_time.present? %> 
                        <h3 class="panel-title pull-left"><%= post.eat_time.strftime('%Y-%m-%d') %></h3>
                        <% else %>
                        <h3 class="panel-title pull-left"><%= post.created_at.strftime('%Y-%m-%d') %></h3>
                        <% end %>

                        <%= link_to  edit_post_path(post), :class => "btn btn-success pull-right" do %>
                            <i class="fa fa-pencil"> </i>
                        <% end %>
                       
                        </div>
                    <div class="list-group">
                      <% if post.photo.file? %>
                        <%= image_tag(post.photo.url(:medium),class: "setimg img-responsive") %>
                      <% else %>
                        <%= image_tag("default.png",class: "setimg img-responsive")%>
                      <%end %>
                      <div class="list-group-item">
                        <h4 class="list-group-item-heading">
                        <% if post.fruitlist.present?  %>
                          <% fruit_tag = post.fruitlist.split(',') %>
                          <% fruit_tag.each do |f| %>
                            <span class="label label-primary"><%= f %></span>
                          <% end %>
                        <% end %>
                       <!--  <span class="label label-primary">香蕉</span>
                        <span class="label label-primary">芭樂</span> -->
                        </h4>
                      </div>
                      <div class="list-group-item">
                        <p class="list-group-item-text"><%= truncate(post.content, :length => 10) %></p>

                      </div>
                    </div>
                    <div class="panel-footer">
                      <div class="col-md-12 text-center">
                        <button class="btn btn-info">
                        <%= link_to "See more", post_path(post), :style=> 'color: white;' %>
            
                        </button>
                      </div>
                    </div>
                </div>
            </div>
            <% if index % 3 == 2 %>
              </div>
            <% end %>
            <% end %>
           

        </div>
    </div>

app/views/posts/new.html.erb
<div class="container">

<h1>New Post</h1>
  <section id="portfolio" style="padding-bottom:20px;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>Diary</h2>
                    <hr class="star-primary">
                </div>
            </div>
        </div>
    </section>
<%= render 'form' %>


</div>	

app/views/posts/show.html.erb
<section id="portfolio" style="padding-bottom:20px;">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>Diary</h2>
                <hr class="star-primary">
            </div>
        </div>
    </div>
</section>


 <div class="container">
        <div class="well">

          <div class="row">
            <div class="col-md-12">
             <% if @post.eat_time.present? %>
                <h3><%= @post.eat_time.strftime('%Y-%m-%d')%></h3>
             <% else %>
                <h3><%= @post.created_at.strftime('%Y-%m-%d') %></h3>
             <% end %>
				<%@fruit_tag.each do |fruit| %>
                <label class="label label-success form_padding"> <%=fruit %> </label> 
                <% end %>
                <hr>
            </div>
          </div>

          <div class="row">
            <div class="col-md-6">
                
				<% if @post.photo.file? %>
				<%=image_tag(@post.photo.url(:large),class: "img-responsive img-rounded", style: "height:400px;width:500px;" ) %>
				<% else %>
                <%= image_tag("default.png",class: "img-responsive img-rounded", style: "height:400px;width:500px;")%>
                <% end %>

            </div>
            <div class="col-md-6 text-center">
                <h3><%=@post.content %><h3>
            </div>
          </div>
          <hr>
          <div class="row">
              <div class="col-md-6">
                  <h4>熱量：<%= @heat %> &nbsp &nbsp kcal </h4>
                  <h4>膳食纖維： <%=@fiber%>&nbsp/&nbsp 25 &nbsp g &nbsp(建議每日攝取量)</h4>
                  <div class="progress">
                  <div class="progress-bar progress-bar-striped active" role="progressbar"
                  aria-valuenow="10" aria-valuemin="0" aria-valuemax="25" 
                  style="width: <%=@fiber/25*100%>%">  <%=@fiber/25*100%>%
                  </div>
                </div>
              </div>
              <div class="col-md-6">
					<% mname =  @big_m_h[0].to_s+".png" %>
					<% vname =  @big_v_h[0].to_s+".png" %>
           
                 <%= image_tag mname, class: "img-circle", height:"100" %>
                 <%= image_tag vname, class: "img-circle", height:"100" %>
                  
              </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-md-6">
            	<div class="alert alert-warning" role="alert">
					<strong style="color:‪#‎d9534f‬">小提示！</strong>
					多吃一點香蕉哦～
				</div>
                <div id="pieChart"></div>
            </div>
            <div class="col-md-6">
            	<%= image_tag("poorguys.png", class: "img-responsive")%>
                
            </div>
          </div>
        </div>
    </div>




<!-- <div class="row"> -->
	
	
<!-- </div> -->

<!-- Tag -->




<%#= link_to 'Edit', edit_post_path(@post) %> |
<%#= link_to 'Back', posts_path %>


<script type="text/javascript">
	
jQuery(document).ready(function($) {


if (<%= @post.fruitlist.present? %> !== false )
{
var pie = new d3pie("pieChart", {
	
	"header": {
		"title": {
			"text": "<%= @post.fruitlist %>",
			"fontSize": 34,
			"font": "courier"
		},
		"subtitle": {
			"text": "每100克含量",
			"color": "#999999",
			"fontSize": 10,
			"font": "courier"
		},
		"location": "pie-center",
		"titleSubtitlePadding": 10
	},
	"footer": {
		//"text": "* This was curious. We're not sure why over several people regard Winnipeg as a Top 15 Fear.",
		"color": "#999999",
		"fontSize": 10,
		"font": "open sans",
		"location": "bottom-left"
	},
	"size": {
		"canvasWidth": 590,
		"pieInnerRadius": "95%",
		"pieOuterRadius": "70%"
	},
	"data": {
		"sortOrder": "random",
		"smallSegmentGrouping": {
			"enabled": true,
			"value": 0
		},
		"content": [
			{
				"label": "熱量 (kcal)",
				"value": <%= @heat.to_i %>,
				"color": "#ccc2b2"
			},
			{
				"label": "水分 (g)",
				"value": <%= @water.to_i %>,
				"color": "#ccc8b2"
			},
			{
				"label": "蛋白質 (g)",
				"value": <%= ('%.2f' % @protein).to_f %>,
				"color": "#b5b2cc"
			},
			{
				"label": "脂肪 (g)",
				"value": <%= ('%.2f' % @fat).to_f %>,
				"color": "#b2bbcc"
			},
			{
				"label": "碳水化合物 (g)",
				"value": <%= ('%.2f' % @carbohydrate).to_f %>,
				"color": "#b2b4cc"
			},
			{
				"label": "膳食纖維 (g)",	
				"value": <%= ('%.2f' % @fiber).to_f %>,
				"color": "#c7ccb2"
			},
			{
				"label": "糖分 (g)",
				"value": <%= ('%.2f' % @sugar).to_f %>,
				"color": "#b2c8cc"
			},
			{
				"label": "鈉 (mg)",
				"value": <%= ('%.2f' % @na).to_f %>,
				"color": "#ccb2b2"
			},
			{
				"label": "鉀 (mg)",
				"value": <%= ('%.2f' % @k).to_f %>,
				"color": "#b2c2cc"
			},
			{
				"label": "鈣 (mg)",
				"value": <%= ('%.2f' % @ca).to_f %>,
				"color": "#b2ccbb"
			},
			{
				"label": "鎂 (mg)",
				"value": <%= ('%.2f' % @mg).to_f %>,
				"color": "#c6b2cc"
			},
			{
				"label": "鐵 (mg)",
				"value": <%= ('%.2f' % @fe).to_f %>,
				"color": "#ccb2c8"
			},
			{
				"label": "鋅 (mg)",
				"value": <%= ('%.2f' % @zn).to_f %>,
				"color": "#b5ccb2"
			},
			{
				"label": "磷 (mg)",
				"value": <%= ('%.2f' % @p).to_f %>,
				"color": "#b2ccc6"
			},
			{
				"label": "維生素A (mg)",
				"value": <%= ('%.2f' % @va).to_f %>,
				"color": "#bbb2cc"
			},
			{
				"label": "維生素E (mg)",
				"value": <%= ('%.2f' % @ve).to_f %>,
				"color": "#b2ccb5"
			},
			{
				"label": "維生素B (mg)",
				"value": <%= ('%.2f' % @vb).to_f %>,
				"color": "#bfccb2"
			},
			{
				"label": "維生素C (mg)",
				"value": <%= ('%.2f' % @vc).to_f %>,
				"color": "#ccb9b2"
			}
		]
	},
	"labels": {
		"outer": {
			"format": "label-value1",
			"pieDistance": 19
		},
		"inner": {
			"format": "none"
		},
		"mainLabel": {
			"fontSize": 11
		},
		"percentage": {
			"color": "#999999",
			"fontSize": 11,
			"decimalPlaces": 0
		},
		"value": {
			"color": "#cccc43",
			"fontSize": 11
		},
		"lines": {
			"enabled": true,
			"color": "#777777"
		},
		"truncation": {
			"enabled": true
		}
	},
	"effects": {
		"pullOutSegmentOnClick": {
			"effect": "linear",
			"speed": 400,
			"size": 8
		}
	},
	"misc": {
		"colors": {
			"segmentStroke": "#000000"
		}
	}
});


}
});


</script>

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

app/views/session/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>